# Site settings
title: R-helper
email: r-helper@users.noreply.github.com
description: R-helper
baseurl: ""
url: "http://r-helper.github.io"
twitter_username: R4_helper
github_username:  r-helper

# Build settings
markdown: kramdown
